#!/bin/bash
OPTION=$(dialog --title  "Bash_Manager" --menu  "Выберите необходимую опцию:" 15 60 4 \
"1" "Пользователи" \
"2" "Права" \
"3" "Сеть и интернет" \
"4" "Дисковые утилиты" \
"5" "Процессы" \
"6" "Настройки менеджера"  3>&1 1>&2 2>&3)
 
exitstatus=$?
if [ $exitstatus = 0 ];  then
	clear
	echo "Your chosen option:" $OPTION
else
	clear
	echo "You chose Cancel."
fi

